spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

infra:
  storage:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:localdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;
    username: admin
    password:

---
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

infra:
  storage:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:devdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;
    username: admin
    password: admin


---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

infra:
  storage:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;
    username: admin
    password: admin

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

infra:
  storage:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:mem:proddb;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE;
    username: admin
    password: admin

